/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weather.project.vistas;

import javax.swing.table.DefaultTableModel;
import weather.project.controlador.MuestraDatos;
import weather.project.principal.WeatherAppFrame;

/**
 *
 * @author fabio
 */
public class PanelCiudades extends javax.swing.JPanel {
    private DefaultTableModel tabla;
    WeatherAppFrame frame;
    /**
     * Creates new form PanelCiudades
     */
    public PanelCiudades(WeatherAppFrame frame) {
        initComponents();
        this.frame = frame;
        cargaTabla();
        
    }
    
    private void cargaTabla(){
         tabla = new DefaultTableModel(new String[]{
            "Ciudad", "Temperatura", "Feels Like", "Estado", "Maxima", "Minima"
        }, 0);
        
        tblCiudades.setModel(tabla);  
        inizializarTabla();
    }
    
    private void inizializarTabla(){
        MuestraDatos muestraDatos = new MuestraDatos(this);
        muestraDatos.MuestraCiudades();
    }
    
    public DefaultTableModel getTabla(){
        return tabla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCiudades = new javax.swing.JTable();

        tblCiudades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCiudades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCiudades;
    // End of variables declaration//GEN-END:variables
}
