/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weather.project.principal;

import weather.project.controlador.MuestraDatos;
import weather.project.vistas.PanelCiudades;
import weather.project.vistas.PanelNuevaCiudad;

/**
 *
 * @author fabio
 */
public class WeatherAppFrame extends javax.swing.JFrame {

    /**
     * Creates new form WeatherAppFrame
     */
    public WeatherAppFrame() {
        initComponents();
    }
    
    private void limpiarPanel(){
        panelContenedor.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCliente = new javax.swing.JMenu();
        mnuAltaCliente = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenu();
        mnuListaCiudades = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        panelContenedor.setPreferredSize(new java.awt.Dimension(800, 800));
        panelContenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelContenedor, java.awt.BorderLayout.CENTER);

        mnuCliente.setText("New");

        mnuAltaCliente.setText("New city");
        mnuAltaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuAltaClienteMousePressed(evt);
            }
        });
        mnuAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaClienteActionPerformed(evt);
            }
        });
        mnuCliente.add(mnuAltaCliente);

        jMenuBar1.add(mnuCliente);

        mnuEmpleados.setText("Ciudades");
        mnuEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuEmpleadosMouseClicked(evt);
            }
        });

        mnuListaCiudades.setText("Ver Ciudades");
        mnuListaCiudades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuListaCiudadesMousePressed(evt);
            }
        });
        mnuListaCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListaCiudadesActionPerformed(evt);
            }
        });
        mnuEmpleados.add(mnuListaCiudades);

        jMenuBar1.add(mnuEmpleados);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaClienteActionPerformed
        // TODO add your handling code here:
        limpiarPanel();
        PanelNuevaCiudad panelNuevaCiudad = new PanelNuevaCiudad(this);
        panelContenedor.add(panelNuevaCiudad, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_mnuAltaClienteActionPerformed

    private void mnuEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuEmpleadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuEmpleadosMouseClicked

    private void mnuAltaClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAltaClienteMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuAltaClienteMousePressed

    private void mnuListaCiudadesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuListaCiudadesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuListaCiudadesMousePressed

    private void mnuListaCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListaCiudadesActionPerformed
        // TODO add your handling code here:
        limpiarPanel();
        PanelCiudades panelCiudades = new PanelCiudades(this);
        panelContenedor.add(panelCiudades, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_mnuListaCiudadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeatherAppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAltaCliente;
    private javax.swing.JMenu mnuCliente;
    private javax.swing.JMenu mnuEmpleados;
    private javax.swing.JMenuItem mnuListaCiudades;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
